name: Free RDP via Cloudflare

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 360

    steps:
    - name: Set RDP Password
      run: |
        net user runneradmin ${{ secrets.RDP_PASSWORD }}
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -name "fDenyTSConnections" -Value 0

    - name: Download Cloudflared
      run: |
        Invoke-WebRequest -Uri https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-windows-amd64.exe -OutFile cloudflared.exe

    - name: Create Cloudflare Tunnel
      run: |
        ./cloudflared.exe tunnel --url rdp://localhost:3389
